### ISSUE TITLE
Hi, you'll have to step down to using [R 4.1.3]...

### ISSUE THREAD

**Issue by Joseph1Otoo** [BroVic/RQDAassist#20]
Hi, you'll have to step down to using [R 4.1.3](https://cran.r-project.org/bin/windows/base/old/$Rversion/R-$Rversion-win.exe) for now. If you don't already have it, you also need [Rtools40](https://github.com/r-windows/rtools-installer/releases/download/2022-02-06/rtools40-x86_64.exe). (Use the links to download)

If you're in R Studio, set it to work with that version via _Tools > Global Options..._. Otherwise, if you're working via a shell, you'll have to reset _PATH_.

_Originally posted by @BroVic in https://github.com/BroVic/RQDAassist/issues/19#issuecomment-1373187560_

**Comment by Joseph1Otoo** [comment]
I have stepped down as you suggested but I seem to have the following error:

Error: package or namespace load failed for 'RQDAassist' in library.dynam(lib, package, package.lib):
 DLL 'purrr' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'

**Comment by Joseph1Otoo** [comment]
A quick follow-up, I have successfully installed the 'purrr' package.

**Comment by BroVic** [comment]
Okay, are you using the current version of this package i e. 0.5.3? And are you on 64-bit Windows?

**Comment by Joseph1Otoo** [comment]
The version of purrr package is 1.0.0 and I am using 64-bit Windows

**Comment by BroVic** [comment]
I'm sorry for not being specific. I meant RQDAassist. The latest is 0.5.3.  

This installation is set to work only on 64-bit architecture. The error you got initially was probably because it was trying to install, via purrr, on the 32-bit as well (since R 4.1 still supports both 32 and 64-bit installation on Windows).

Note that the reason you got now and the first are different is because the 2 installations are accessing different libraries on your computer. R versions with different MINOR versions (the middle digit) use different library directories. Thus, the exact packages installed (and their versions) could differ. In your case, the you had **purrr** in the 4.2 library, but not in the 4.1. i hope this is clear. 

If you retry the installation, per the instructions in the README it will stop at least once, and you will have to run `library(RGtk2)` to install Gtk+ when prompted and then you run `RQDAassist::install()` again. 

If you encounter a problem, share the output of `sessiinInfo()` with the error message.

**Comment by BroVic** [comment]
In the absence of further comments, I presume the issue is resolved. Feel free to reopen if this is not the case.

**Comment by Joseph1Otoo** [comment]
Sorry I was quite busy and could not respond as I should. I downloaded the latest version of the package and installed locally but still have issues. I ran sessionInfo() and I had the following:

R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_Ghana.1252  LC_CTYPE=English_Ghana.1252   
[3] LC_MONETARY=English_Ghana.1252 LC_NUMERIC=C                  
[5] LC_TIME=English_Ghana.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.7.2          prettyunits_1.1.1 crayon_1.5.2      withr_2.5.0      
 [5] rprojroot_2.0.3   R6_2.5.1          cli_3.5.0         curl_4.3.3       
 [9] remotes_2.4.2     rstudioapi_0.14   callr_3.7.3       desc_1.4.2       
[13] tools_4.1.3       compiler_4.1.3    processx_3.8.0    pkgbuild_1.4.0

**Comment by BroVic** [comment]
Okay, please also post the error message. Thanks.

**Comment by Joseph1Otoo** [comment]
This is the error message:


 installing *source* package 'RQDAassist' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'RQDAassist'
    finding HTML links ... done
    install                                 html  
    make_FileList                           html  
    read_transcript                         html  
    retrieve_codingtable                    html  
    search_codes                            html  
    start                                   html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'RQDAassist' in library.dynam(lib, package, package.lib):
 DLL 'purrr' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/piana/OneDrive/Documents/R/win-library/4.1/RQDAassist'
Warning in install.packages :
  installation of package ‘C:/Users/piana/Downloads/RQDAassist_0.5.3.tar.gz’ had non-zero exit status

**Comment by BroVic** [comment]
`removing 'C:/Users/piana/OneDrive/Documents/R/win-library/4.1/RQDAassist`

I would advise you to review your entire R installation. Apparently, you're using a cloud folder, which is prone to problems. For Windows, use a regular directory under "Documents".

**Comment by Joseph1Otoo** [comment]
I have created new folder that is not dependent on the cloud. I have been able to install most of the packages with the exception of cairoDevice and gWidgetsRGtk2. These are dependent packages for RQDA.

**Comment by BroVic** [comment]
Okay, progress. Please post the error you got when you ran `RQDAassist::install()` as well as the output of `sessionInfo()`. Also note that {gWidgetsRGtk2} cannot be installed until you first run `library(RGtk2)` and follow the prompt to install {Gtk+}. Again, you can refer to the README of this repo for guidance.

**Comment by Joseph1Otoo** [comment]
Here you go:

> RQDAassist::install()
Your system is ready to build packages!
Installing 'cairoDevice' ... 
Downloading package from url: https://cran.r-project.org/src/contrib/Archive/cairoDevice/cairoDevice_2.28.2.1.tar.gz
Installing package into ‘C:/Users/JoeP/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'cairoDevice' ...
** package 'cairoDevice' successfully unpacked and MD5 sums checked
** using staged installation
** libs
"C:/Users/JoeP/Documents/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.3/include" -DNDEBUG -D_R_=1 -DUSE_R=1 -mms-bitfields -I/include/gtk-2.0 -I/lib/gtk-2.0/include -I/include/atk-1.0 -I/include/cairo -I/include/pango-1.0 -I/include/glib-2.0 -I/lib/glib-2.0/include -I/include/cairo -I/include/gdk-pixbuf-2.0 -I/include -IC:/PROGRA~1/R/R-41~1.3/include -DR_LEGACY_S_DEFS=1         -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c R_init_cairoDevice.c -o R_init_cairoDevice.o
"C:/Users/JoeP/Documents/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.3/include" -DNDEBUG -D_R_=1 -DUSE_R=1 -mms-bitfields -I/include/gtk-2.0 -I/lib/gtk-2.0/include -I/include/atk-1.0 -I/include/cairo -I/include/pango-1.0 -I/include/glib-2.0 -I/lib/glib-2.0/include -I/include/cairo -I/include/gdk-pixbuf-2.0 -I/include -IC:/PROGRA~1/R/R-41~1.3/include -DR_LEGACY_S_DEFS=1         -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c cairoDevice.c -o cairoDevice.o
In file included from cairoDevice.c:1:
cairoDevice.h:1:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-41~1.3/etc/x64/Makeconf:238: cairoDevice.o] Error 1
ERROR: compilation failed for package 'cairoDevice'
* removing 'C:/Users/JoeP/Documents/R/win-library/4.1/cairoDevice'
Done
Package already installed: gWidgets 
Installing 'gWidgetsRGtk2' ... 
Downloading package from url: https://cran.r-project.org/src/contrib/Archive/gWidgetsRGtk2/gWidgetsRGtk2_0.0-86.tar.gz
Installing package into ‘C:/Users/JoeP/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
ERROR: dependency 'cairoDevice' is not available for package 'gWidgetsRGtk2'
* removing 'C:/Users/JoeP/Documents/R/win-library/4.1/gWidgetsRGtk2'
Done
Installing 'RQDA' ... 
Downloading package from url: https://cran.r-project.org/src/contrib/Archive/RQDA/RQDA_0.3-1.tar.gz
Installing package into ‘C:/Users/JoeP/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
ERROR: dependency 'gWidgetsRGtk2' is not available for package 'RQDA'
* removing 'C:/Users/JoeP/Documents/R/win-library/4.1/RQDA'
Done
Warning messages:
1: In i.p(...) :
  installation of package ‘C:/Users/JoeP/AppData/Local/Temp/RtmpuW8E6B/remotes4834381c3537/cairoDevice’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘C:/Users/JoeP/AppData/Local/Temp/RtmpuW8E6B/remotes4834485222d1/gWidgetsRGtk2’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘C:/Users/JoeP/AppData/Local/Temp/RtmpuW8E6B/remotes48345f2d16e/RQDA’ had non-zero exit status
> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_Ghana.1252  LC_CTYPE=English_Ghana.1252   
[3] LC_MONETARY=English_Ghana.1252 LC_NUMERIC=C                  
[5] LC_TIME=English_Ghana.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9        pillar_1.8.1      urlchecker_1.0.1  compiler_4.1.3   
 [5] later_1.3.0       remotes_2.4.2     prettyunits_1.1.1 profvis_0.3.7    
 [9] tools_4.1.3       readtext_0.81     digest_0.6.31     pkgbuild_1.4.0   
[13] bit_4.0.5         pkgload_1.3.2     tibble_3.1.8      RSQLite_2.2.20   
[17] memoise_2.0.1     lifecycle_1.0.3   pkgconfig_2.0.3   rlang_1.0.6      
[21] shiny_1.7.4       DBI_1.1.3         cli_3.6.0         rstudioapi_0.14  
[25] fastmap_1.1.0     withr_2.5.0       httr_1.4.4        dplyr_1.0.10     
[29] stringr_1.5.0     generics_0.1.3    fs_1.5.2          vctrs_0.5.1      
[33] htmlwidgets_1.6.1 devtools_2.4.5    tidyselect_1.2.0  RQDAassist_0.5.4 
[37] bit64_4.0.5       data.table_1.14.6 glue_1.6.2        R6_2.5.1         
[41] processx_3.8.0    fansi_1.0.3       sessioninfo_1.2.2 purrr_1.0.1      
[45] callr_3.7.3       blob_1.2.3        magrittr_2.0.3    usethis_2.1.6    
[49] promises_1.2.0.1  ps_1.7.2          ellipsis_0.3.2    htmltools_0.5.4  
[53] assertthat_0.2.1  mime_0.12         xtable_1.8-4      httpuv_1.6.8     
[57] utf8_1.2.2        stringi_1.7.12    miniUI_0.1.1.1    cachem_1.0.6     
[61] crayon_1.5.2

**Comment by BroVic** [comment]
Gtk+ is missing, which will be installed when after you've installed RGtk2 and then run `library(RGtk2)`. For avoidance of doubt, you should check if it is present with
```
"RGtk2" %in% .packages(all.available = TRUE)
```
and the output should be `TRUE` if it is present. Then run

```
library(RGtk2)
```
and a dialog will come up for you to install Gtk+.

If RGtk2 does not exist, you can use this to install it and follow the steps already outlined
```
RQDAassist::install_rgtk2_and_deps()
```

**Comment by Joseph1Otoo** [comment]
It just did not work for me. RGtk2 is already installed to gether with Gtk+. If I use library(RGtk2) no dialogue pops up. Implications are that Gtk+ has already been installed.

**Comment by BroVic** [comment]
Something's wrong with your RGtk2/Gtk setup.

Do this:
```
remove.packages("RGtk2")
```
and reinstall it as before. 

The error says {cairoDevice} couldn't be compiled because a file that is part of the GTK distribution was missing. Perhaps it has something to do with how you installed things earlier.

**Comment by Joseph1Otoo** [comment]
I have removed package - RGtk2 and reinstalled, it did not work. I have uninstalled R and reinstalled, it did not work. I stepped down to R version 4.0.3, it also did not work.
Thanks for the effort.

**Comment by BroVic** [comment]
Sorry for the late response, I was tied up in some other activity.

1. Was the reinstallation of RGtk2 successful?
2. If yes, were you able to install Gtk+?
3. If yes, did you get exactly the same error?

Don't give up, it's also a learning experience :)

**Comment by BroVic** [comment]
I was able to reproduce your error and discovered that the problem you were facing was the {cairoDevice} was unable to find the files it needed for compilation since you don't have the GTK distribution (the one you install via the dialog is placed locally within the RGtk2 library, and is accessible only to that package. I have done an update to address the situation and will make a release later this week. 

For now, I built the {cairoDevice} package for you, so you are free to download and install it **[here](https://drive.google.com/file/d/1q67iuDrr_DNkAf0V6VMFi9JQ-G7NgvUN/view?usp=sharing)**. If you're using R Studio, you can do this via the **Install** button on the *Packages* pane - select the downloaded ZIP file and click the appropriate button. You can also use `install.packages("path/to/cairoDevice_2.28.2.1.zip")`.

**Comment by BroVic** [comment]
@Joseph1Otoo I have made an update on the `dev` branch of this repository. It is version 0.5.4.9003 and you can install it with this code:

```
remotes::install_github("BroVic/RQDAassist", ref = "dev")
```

**Comment by Joseph1Otoo** [comment]
@BroVic, thank you so much for the effort and patience. I have successfully installed RQDA.

Thanks.
